spring:
  application:
    name:
      user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: {DB_URL}
    username: {DB_NAME}
    password: {DB_PASSWORD}

server:
  port: 8080